### ISSUE TITLE
sunset

### ISSUE THREAD

**Issue by jeacott1** [vert-x3/vertx-jgroups#30] opened 2017-05-21 22:45 UTC
If this project is to be retired and replaced by infinispan, it should be maintained until the infinispan implementation can at least come somewhere close to matching performance.
at the moment infinispan makes the eventbus orders of magnitude slower.

https://github.com/vert-x3/vertx-infinispan/issues/33

**Comment by tsegismont** [comment] 2017-05-22 07:38
Can you file an issue on the vertx-infinispan repo with a test
demonstrating the performance issue? Thank you

**Comment by tsegismont** [comment] 2017-05-22 08:57
Also, vertx-infinispan maintains a cache for event bus subscriptions so
once it is populated the sending performance should not depend on ISPN's
performance.

Note that the cache logic is the same as in Hazelcast, and it suffers from
this issue: https://github.com/vert-x3/vertx-hazelcast/issues/73

Your test might fall in this issue and that is why we need it to confirm.

2017-05-22 9:38 GMT+02:00 Thomas SEGISMONT <tsegismont@gmail.com>:

> Can you file an issue on the vertx-infinispan repo with a test
> demonstrating the performance issue? Thank you
>

**Comment by jeacott1** [comment] 2017-05-25 00:13
My test could well fall into many traps, but my real world usage simply pipes messages from a vertx listener to the eventbus. jgroups works very well, hazelcast and infinispan do not.
hazelcast is also almost useless in the wild re its performance for me. the only viable alternative to jgroups at this point afaik is ignite, but its also significantly slower than jgroups on the send side of the bus.

because the infinispan manager cannot be run with any other manager on the classpath, switching providers is unfortunately a manual process. My test is somewhat agricultural, but reflects well with my real world experience.  I commented with a link in the infinispan thread, but here for clarity https://github.com/jeacott1/vertx-clustermanager-simpletest

**Comment by tsegismont** [comment] 2017-06-09 16:45
@jeacott1 I had a look at your test. It falls in the issue I pointed out (vert-x3/vertx-hazelcast#73).

I made some changes (see https://github.com/jeacott1/vertx-clustermanager-simpletest/pull/1) so that the subscription cache gets initialized and then the ISPN impl outperforms the JGroups implementation.

The fix in Hazelcast and Infinispan is planned for 3.5

**Comment by jeacott1** [comment] 2017-06-14 20:28
so the only difference i see is that you are sending an extra initial message to the same address instead of the 'initialise' address i had setup in order to attempt the prepopulate cache thing. Id assume that the network topology that needs caching wouldn't change wrt target address, so why are they apparently cached independently?

**Comment by tsegismont** [comment] 2017-06-15 07:22
The network topology is known as soon as the node is started. What the
clustered event bus needs to know when sending a message is where are the
subscribers for that address. Subscriptions are stored in a multimap, the
key being the address and the values are the nodes having a subscriber.
When you send a message, the cluster manager gets the list of nodes with a
subscriber and then caches it. That's why you need to send a first message
to the same address, not to any address.

A fix for vert-x3/vertx-hazelcast#73 is planned for 3.5

2017-06-14 22:28 GMT+02:00 jeacott1 <notifications@github.com>:

**Comment by jeacott1** [comment] 2017-06-20 04:31
ok, so for my usecase where I have literally millions of addresses, thats kinda useless. will the fix in 3.5 address my needs?

**Comment by tsegismont** [comment] 2017-06-20 09:24
I guess it would be difficult to keep track of "warmed-up" addresses if you
have millions of them, yes.

Out of curiosity, why do you need so many of them?

2017-06-20 6:31 GMT+02:00 jeacott1 <notifications@github.com>:

**Comment by jeacott1** [comment] 2017-06-24 00:59
discovery of connected devices, and as boxes drop, many many connections will re-establish elsewhere very quickly. is there any way to configure redis or something as common cache?

out of interest, if an address (A) is registered on host (A) and a message is sent to address (B) on host (B) expecting a reply, is there any way to send the address+host (A) at the same time so that the address can be cached with (B) at that point? seems redundant for B to have to discover A when it could have received the appropriate data already.

**Comment by jeacott1** [comment] 2017-07-17 00:09
also, I'm not clear on how a fix in https://github.com/vert-x3/vertx-hazelcast/issues/73 will fix the infinispan issue. is #73 actually a vertx core fix, not a hazelcast fix?

**Comment by tsegismont** [comment] 2017-07-18 08:17
Both vertx-hazelcast and vertx-infinispan use a subscription cache. The
code is the same. When the issue is fixed in vertx-hazelcast, the fix will
be ported over to vertx-infiispan.

2017-07-17 2:09 GMT+02:00 jeacott1 <notifications@github.com>:

**Comment by tsegismont** [comment] 2017-08-03 13:26
Closing as vert-x3/vertx-infinispan#33 is now fixed

**Closed as completed by tsegismont** 2017-08-03 13:26 UTC
